### ISSUE TITLE
Add highlighting of the next moves instead of pressing button to execute them

### ISSUE THREAD

**Issue by SolsticeSpectrum** [wtfseanscool/lichess-autoplay#1]
It would allow one to study why the engine wants to make the move and perhaps choose a different move if using different engine like leela with networks like maia

Here is how different chess.com cheat does it. Now problem is that you would have to calculate the correct pixel values of transform
https://github.com/IOKernel/Sangatsu/blob/master/utils/helpers.py#L141

```
<cg-board>
    <square class="selected" style="transform: translate(224px, 336px);"></square><!-- highlighting -->
    <piece class="white knight" style="transform: translate(56px, 392px);"></piece><!-- chess pieces -->
</cg-board>
```
Also keep in mind board rotation as it flips the values completely. Also keep in mind size of the board as that also flips the numbers completely. Yeah it will be slightly harder than chess.com that positions the highlighting automatically when injected

```
<chess-board class="board">
    <div class="highlight square-42" style="background-color: rgb(94, 215, 241); opacity: 0.5;"
        data-test-element="highlight"></div><!-- highlighting -->
    <div class="piece wr square-11" style=""></div><!-- chess pieces -->
</chess-board>
```

**Comment by wtfseanscool** [comment]
@DarkReaper231 
Added some basic functionality in this commit: cd2ccffd4059c3f089c84f65c050ac3f0c9cb31d
